//********************************************* Variabili TOP *************************************************************************
std::vector<int> B8_TOP_etafirech;
std::vector<int> B8_TOP_etafirechFINE;
std::vector<float> B8_TOP_etafireleading;
std::vector<float> B8_TOP_etafireleadingFINE;
std::vector<int> B8_TOP_etafiretrailch;
std::vector<float> B8_TOP_etafiretrailing;
std::vector<float> B8_TOP_etaWidth;
std::vector<float> B8_TOP_etaWidthFINE;
Float_t B8_TOP_etaWidthmax;
Int_t B8_TOP_etaWidthmaxch;
std::vector<int> B8_TOP_phifirech;
std::vector<int> B8_TOP_phifirechFINE;
std::vector<float> B8_TOP_phifireleading;
std::vector<float> B8_TOP_phifireleadingFINE;
std::vector<int> B8_TOP_phifiretrailch;
std::vector<float> B8_TOP_phifiretrailing;
std::vector<float> B8_TOP_phiWidth;
std::vector<float> B8_TOP_phiWidthFINE;
Float_t B8_TOP_phiWidthmax;
Int_t B8_TOP_phiWidthmaxch;
Int_t B8_TOP_etaevent;
Int_t B8_TOP_etatroppilead;
Int_t B8_TOP_etatroppitrail;
Int_t B8_TOP_phievent;
Int_t B8_TOP_phitroppilead;
Int_t B8_TOP_phitroppitrail;
Int_t B8_TOP_etanumberofclusters;
std::vector<int> B8_TOP_etaCS;
std::vector<int> B8_TOP_etaCSFINE;
std::vector<int> B8_TOP_etaCSminch;
std::vector<int> B8_TOP_etaCSminchFINE;
std::vector<float> B8_TOP_etaCStime;
std::vector<float> B8_TOP_etaCStimeFINE;
Int_t B8_TOP_phinumberofclusters;
std::vector<int> B8_TOP_phiCS;
std::vector<int> B8_TOP_phiCSFINE;
std::vector<int> B8_TOP_phiCSminch;
std::vector<int> B8_TOP_phiCSminchFINE;
std::vector<float> B8_TOP_phiCStime;
std::vector<float> B8_TOP_phiCStimeFINE;
Double_t B8_TOP_ANDeff;
Double_t B8_TOP_etaeff;
Double_t B8_TOP_phieff;
Double_t B8_TOP_etaeffFINE;
Double_t B8_TOP_phieffFINE;

//********************************************* Variabili MID *************************************************************************
std::vector<int> B8_MID_etafirech;
std::vector<int> B8_MID_etafirechFINE;
std::vector<float> B8_MID_etafireleading;
std::vector<float> B8_MID_etafireleadingFINE;
std::vector<int> B8_MID_etafiretrailch;
std::vector<float> B8_MID_etafiretrailing;
std::vector<float> B8_MID_etaWidth;
std::vector<float> B8_MID_etaWidthFINE;
Float_t B8_MID_etaWidthmax;
Int_t B8_MID_etaWidthmaxch;
std::vector<int> B8_MID_phifirech;
std::vector<int> B8_MID_phifirechFINE;
std::vector<float> B8_MID_phifireleading;
std::vector<float> B8_MID_phifireleadingFINE;
std::vector<int> B8_MID_phifiretrailch;
std::vector<float> B8_MID_phifiretrailing;
std::vector<float> B8_MID_phiWidth;
std::vector<float> B8_MID_phiWidthFINE;
Float_t B8_MID_phiWidthmax;
Int_t B8_MID_phiWidthmaxch;
Int_t B8_MID_etaevent;
Int_t B8_MID_etatroppilead;
Int_t B8_MID_etatroppitrail;
Int_t B8_MID_phievent;
Int_t B8_MID_phitroppilead;
Int_t B8_MID_phitroppitrail;
Int_t B8_MID_etanumberofclusters;
std::vector<int> B8_MID_etaCS;
std::vector<int> B8_MID_etaCSFINE;
std::vector<int> B8_MID_etaCSminch;
std::vector<int> B8_MID_etaCSminchFINE;
std::vector<float> B8_MID_etaCStime;
std::vector<float> B8_MID_etaCStimeFINE;
Int_t B8_MID_phinumberofclusters;
std::vector<int> B8_MID_phiCS;
std::vector<int> B8_MID_phiCSFINE;
std::vector<int> B8_MID_phiCSminch;
std::vector<int> B8_MID_phiCSminchFINE;
std::vector<float> B8_MID_phiCStime;
std::vector<float> B8_MID_phiCStimeFINE;
Double_t B8_MID_ANDeff;
Double_t B8_MID_etaeff;
Double_t B8_MID_phieff;
Double_t B8_MID_etaeffFINE;
Double_t B8_MID_phieffFINE;

//********************************************* Variabili BOT *************************************************************************
std::vector<int> B8_BOT_etafirech;
std::vector<int> B8_BOT_etafirechFINE;
std::vector<float> B8_BOT_etafireleading;
std::vector<float> B8_BOT_etafireleadingFINE;
std::vector<int> B8_BOT_etafiretrailch;
std::vector<float> B8_BOT_etafiretrailing;
std::vector<float> B8_BOT_etaWidth;
std::vector<float> B8_BOT_etaWidthFINE;
Float_t B8_BOT_etaWidthmax;
Int_t B8_BOT_etaWidthmaxch;
std::vector<int> B8_BOT_phifirech;
std::vector<int> B8_BOT_phifirechFINE;
std::vector<float> B8_BOT_phifireleading;
std::vector<float> B8_BOT_phifireleadingFINE;
std::vector<int> B8_BOT_phifiretrailch;
std::vector<float> B8_BOT_phifiretrailing;
std::vector<float> B8_BOT_phiWidth;
std::vector<float> B8_BOT_phiWidthFINE;
Float_t B8_BOT_phiWidthmax;
Int_t B8_BOT_phiWidthmaxch;
Int_t B8_BOT_etaevent;
Int_t B8_BOT_etatroppilead;
Int_t B8_BOT_etatroppitrail;
Int_t B8_BOT_phievent;
Int_t B8_BOT_phitroppilead;
Int_t B8_BOT_phitroppitrail;
Int_t B8_BOT_etanumberofclusters;
std::vector<int> B8_BOT_etaCS;
std::vector<int> B8_BOT_etaCSFINE;
std::vector<int> B8_BOT_etaCSminch;
std::vector<int> B8_BOT_etaCSminchFINE;
std::vector<float> B8_BOT_etaCStime;
std::vector<float> B8_BOT_etaCStimeFINE;
Int_t B8_BOT_phinumberofclusters;
std::vector<int> B8_BOT_phiCS;
std::vector<int> B8_BOT_phiCSFINE;
std::vector<int> B8_BOT_phiCSminch;
std::vector<int> B8_BOT_phiCSminchFINE;
std::vector<float> B8_BOT_phiCStime;
std::vector<float> B8_BOT_phiCStimeFINE;
Double_t B8_BOT_ANDeff;
Double_t B8_BOT_etaeff;
Double_t B8_BOT_phieff;
Double_t B8_BOT_etaeffFINE;
Double_t B8_BOT_phieffFINE;

//****************************************** VARIABILI GENERALI ***********************************
int B8_Trip_etacounter;
int B8_Trip_phicounter;
int B8_TOP_BOT_etacounter;
int B8_MID_BOT_etacounter;
int B8_TOP_MID_etacounter;
int B8_TOP_BOT_phicounter;
int B8_MID_BOT_phicounter;
int B8_TOP_MID_phicounter;
int B8_TripAND_counter;
int B8_TOP_MID_ANDcounter;
int B8_TOP_BOT_ANDcounter;
int B8_MID_BOT_ANDcounter;
int B8_Trip_etacounterTOPFINE;
int B8_Trip_etacounterMIDFINE;
int B8_Trip_etacounterBOTFINE;    
int B8_TOP_BOT_etacounterFINE; 
int B8_MID_BOT_etacounterFINE; 
int B8_TOP_MID_etacounterFINE;

int B8_Trip_phicounterTOPFINE;   
int B8_Trip_phicounterMIDFINE;   
int B8_Trip_phicounterBOTFINE;    
int B8_TOP_BOT_phicounterFINE; 
int B8_MID_BOT_phicounterFINE; 
int B8_TOP_MID_phicounterFINE;

int B8_MID_BOT_etaphiflagFINE;
int B8_MID_BOT_etaphicounterFINE;
int B8_TOP_BOT_etaphiflagFINE;
int B8_TOP_BOT_etaphicounterFINE; 
int B8_TOP_MID_etaphiflagFINE;
int B8_TOP_MID_etaphicounterFINE;
////////////////////////////////////////////////////////////////// Analysis branches///////////////////////////////////////////////////
//********************************************* Branches TOP *************************************************************************
  OutTree->Branch("B8_TOP_etafirech" &B8_TOP_etafirech);
  OutTree->Branch("B8_TOP_etafirechFINE" &B8_TOP_etafirechFINE);
  OutTree->Branch("B8_TOP_etafireleading" &B8_TOP_etafireleading);
  OutTree->Branch("B8_TOP_etafireleadingFINE" &B8_TOP_etafireleadingFINE);
  OutTree->Branch("B8_TOP_etafiretrailing" &B8_TOP_etafiretrailing);
  OutTree->Branch("B8_TOP_etafiretrailch" &B8_TOP_etafiretrailch);
  OutTree->Branch("B8_TOP_etaWidth" &B8_TOP_etaWidth);
  OutTree->Branch("B8_TOP_etaWidthFINE" &B8_TOP_etaWidthFINE);
  OutTree->Branch("B8_TOP_etaWidthmax" &B8_TOP_etaWidthmax);
  OutTree->Branch("B8_TOP_etaWidthmaxch" &B8_TOP_etaWidthmaxch);
  OutTree->Branch("B8_TOP_etaevent" &B8_TOP_etaevent);
  OutTree->Branch("B8_TOP_phifirech" &B8_TOP_phifirech);
  OutTree->Branch("B8_TOP_phifirechFINE" &B8_TOP_phifirechFINE);
  OutTree->Branch("B8_TOP_phifireleading" &B8_TOP_phifireleading);
  OutTree->Branch("B8_TOP_phifireleadingFINE" &B8_TOP_phifireleadingFINE);
  OutTree->Branch("B8_TOP_phifiretrailch" &B8_TOP_phifiretrailch);
  OutTree->Branch("B8_TOP_phifiretrailing" &B8_TOP_phifiretrailing);
  OutTree->Branch("B8_TOP_phiWidth" &B8_TOP_phiWidth);
  OutTree->Branch("B8_TOP_phiWidthFINE" &B8_TOP_phiWidthFINE);
  OutTree->Branch("B8_TOP_phiWidthmax" &B8_TOP_phiWidthmax);
  OutTree->Branch("B8_TOP_phiWidthmaxch" &B8_TOP_phiWidthmaxch);
  OutTree->Branch("B8_TOP_phievent" &B8_TOP_phievent);
  OutTree->Branch("B8_TOP_etaCS" &B8_TOP_etaCS);
  OutTree->Branch("B8_TOP_etaCSFINE" &B8_TOP_etaCSFINE);
  OutTree->Branch("B8_TOP_etanumberofclusters" &B8_TOP_etanumberofclusters);
  OutTree->Branch("B8_TOP_etaCStime" &B8_TOP_etaCStime);
  OutTree->Branch("B8_TOP_etaCStimeFINE" &B8_TOP_etaCStimeFINE);
  OutTree->Branch("B8_TOP_etaCSminch" &B8_TOP_etaCSminch);
  OutTree->Branch("B8_TOP_etaCSminchFINE" &B8_TOP_etaCSminchFINE);
  OutTree->Branch("B8_TOP_phiCS" &B8_TOP_phiCS);
  OutTree->Branch("B8_TOP_phiCSFINE" &B8_TOP_phiCSFINE);
  OutTree->Branch("B8_TOP_phinumberofclusters" &B8_TOP_phinumberofclusters);
  OutTree->Branch("B8_TOP_phiCStime" &B8_TOP_phiCStime);
  OutTree->Branch("B8_TOP_phiCStimeFINE" &B8_TOP_phiCStimeFINE);
  OutTree->Branch("B8_TOP_phiCSminch" &B8_TOP_phiCSminch);
  OutTree->Branch("B8_TOP_phiCSminchFINE" &B8_TOP_phiCSminchFINE);
//********************************************* Branches MID *************************************************************************
  OutTree->Branch("B8_MID_etafirech" &B8_MID_etafirech);
  OutTree->Branch("B8_MID_etafirechFINE" &B8_MID_etafirechFINE);
  OutTree->Branch("B8_MID_etafireleading" &B8_MID_etafireleading);
  OutTree->Branch("B8_MID_etafireleadingFINE" &B8_MID_etafireleadingFINE);
  OutTree->Branch("B8_MID_etafiretrailing" &B8_MID_etafiretrailing);
  OutTree->Branch("B8_MID_etafiretrailch" &B8_MID_etafiretrailch);
  OutTree->Branch("B8_MID_etaWidth" &B8_MID_etaWidth);
  OutTree->Branch("B8_MID_etaWidthFINE" &B8_MID_etaWidthFINE);
  OutTree->Branch("B8_MID_etaWidthmax" &B8_MID_etaWidthmax);
  OutTree->Branch("B8_MID_etaWidthmaxch" &B8_MID_etaWidthmaxch);
  OutTree->Branch("B8_MID_etaevent" &B8_MID_etaevent);
  OutTree->Branch("B8_MID_phifirech" &B8_MID_phifirech);
  OutTree->Branch("B8_MID_phifirechFINE" &B8_MID_phifirechFINE);
  OutTree->Branch("B8_MID_phifireleading" &B8_MID_phifireleading);
  OutTree->Branch("B8_MID_phifireleadingFINE" &B8_MID_phifireleadingFINE);
  OutTree->Branch("B8_MID_phifiretrailch" &B8_MID_phifiretrailch);
  OutTree->Branch("B8_MID_phifiretrailing" &B8_MID_phifiretrailing);
  OutTree->Branch("B8_MID_phiWidth" &B8_MID_phiWidth);
  OutTree->Branch("B8_MID_phiWidthFINE" &B8_MID_phiWidthFINE);
  OutTree->Branch("B8_MID_phiWidthmax" &B8_MID_phiWidthmax);
  OutTree->Branch("B8_MID_phiWidthmaxch" &B8_MID_phiWidthmaxch);
  OutTree->Branch("B8_MID_phievent" &B8_MID_phievent);
  OutTree->Branch("B8_MID_etaCS" &B8_MID_etaCS);
  OutTree->Branch("B8_MID_etaCSFINE" &B8_MID_etaCSFINE);
  OutTree->Branch("B8_MID_etanumberofclusters" &B8_MID_etanumberofclusters);
  OutTree->Branch("B8_MID_etaCStime" &B8_MID_etaCStime);
  OutTree->Branch("B8_MID_etaCStimeFINE" &B8_MID_etaCStimeFINE);
  OutTree->Branch("B8_MID_etaCSminch" &B8_MID_etaCSminch);
  OutTree->Branch("B8_MID_etaCSminchFINE" &B8_MID_etaCSminchFINE);
  OutTree->Branch("B8_MID_phiCS" &B8_MID_phiCS);
  OutTree->Branch("B8_MID_phiCSFINE" &B8_MID_phiCSFINE);
  OutTree->Branch("B8_MID_phinumberofclusters" &B8_MID_phinumberofclusters);
  OutTree->Branch("B8_MID_phiCStime" &B8_MID_phiCStime);
  OutTree->Branch("B8_MID_phiCStimeFINE" &B8_MID_phiCStimeFINE);
  OutTree->Branch("B8_MID_phiCSminch" &B8_MID_phiCSminch);
  OutTree->Branch("B8_MID_phiCSminchFINE" &B8_MID_phiCSminchFINE);
//********************************************* Branches BOT *************************************************************************
  OutTree->Branch("B8_BOT_etafirech" &B8_BOT_etafirech);
  OutTree->Branch("B8_BOT_etafirechFINE" &B8_BOT_etafirechFINE);
  OutTree->Branch("B8_BOT_etafireleading" &B8_BOT_etafireleading);
  OutTree->Branch("B8_BOT_etafireleadingFINE" &B8_BOT_etafireleadingFINE);
  OutTree->Branch("B8_BOT_etafiretrailing" &B8_BOT_etafiretrailing);
  OutTree->Branch("B8_BOT_etafiretrailch" &B8_BOT_etafiretrailch);
  OutTree->Branch("B8_BOT_etaWidth" &B8_BOT_etaWidth);
  OutTree->Branch("B8_BOT_etaWidthFINE" &B8_BOT_etaWidthFINE);
  OutTree->Branch("B8_BOT_etaWidthmax" &B8_BOT_etaWidthmax);
  OutTree->Branch("B8_BOT_etaWidthmaxch" &B8_BOT_etaWidthmaxch);
  OutTree->Branch("B8_BOT_etaevent" &B8_BOT_etaevent);
  OutTree->Branch("B8_BOT_phifirech" &B8_BOT_phifirech);
  OutTree->Branch("B8_BOT_phifirechFINE" &B8_BOT_phifirechFINE);
  OutTree->Branch("B8_BOT_phifireleading" &B8_BOT_phifireleading);
  OutTree->Branch("B8_BOT_phifireleadingFINE" &B8_BOT_phifireleadingFINE);
  OutTree->Branch("B8_BOT_phifiretrailch" &B8_BOT_phifiretrailch);
  OutTree->Branch("B8_BOT_phifiretrailing" &B8_BOT_phifiretrailing);
  OutTree->Branch("B8_BOT_phiWidth" &B8_BOT_phiWidth);
  OutTree->Branch("B8_BOT_phiWidthFINE" &B8_BOT_phiWidthFINE);
  OutTree->Branch("B8_BOT_phiWidthmax" &B8_BOT_phiWidthmax);
  OutTree->Branch("B8_BOT_phiWidthmaxch" &B8_BOT_phiWidthmaxch);
  OutTree->Branch("B8_BOT_phievent" &B8_BOT_phievent);
  OutTree->Branch("B8_BOT_etaCS" &B8_BOT_etaCS);
  OutTree->Branch("B8_BOT_etaCSFINE" &B8_BOT_etaCSFINE);
  OutTree->Branch("B8_BOT_etanumberofclusters" &B8_BOT_etanumberofclusters);
  OutTree->Branch("B8_BOT_etaCStime" &B8_BOT_etaCStime);
  OutTree->Branch("B8_BOT_etaCStimeFINE" &B8_BOT_etaCStimeFINE);
  OutTree->Branch("B8_BOT_etaCSminch" &B8_BOT_etaCSminch);
  OutTree->Branch("B8_BOT_etaCSminchFINE" &B8_BOT_etaCSminchFINE);
  OutTree->Branch("B8_BOT_phiCS" &B8_BOT_phiCS);
  OutTree->Branch("B8_BOT_phiCSFINE" &B8_BOT_phiCSFINE);
  OutTree->Branch("B8_BOT_phinumberofclusters" &B8_BOT_phinumberofclusters);
  OutTree->Branch("B8_BOT_phiCStime" &B8_BOT_phiCStime);
  OutTree->Branch("B8_BOT_phiCStimeFINE" &B8_BOT_phiCStimeFINE);
  OutTree->Branch("B8_BOT_phiCSminch" &B8_BOT_phiCSminch);
  OutTree->Branch("B8_BOT_phiCSminchFINE" &B8_BOT_phiCSminchFINE);
///////////////////////////////////////////////////////////////// Ana branches///////////////////////////////////////////////////
//********************************************* Branches TOP *************************************************************************
  AnalTree->Branch("B8_TOP_ANDeff" &B8_TOP_ANDeff "B8_TOP_ANDeff/D");
  AnalTree->Branch("B8_TOP_etaeff" &B8_TOP_etaeff "B8_TOP_etaeff/D");
  AnalTree->Branch("B8_TOP_phieff" &B8_TOP_phieff "B8_TOP_phieff/D");
  AnalTree->Branch("B8_TOP_etaeffFINE" &B8_TOP_etaeffFINE "B8_TOP_etaeffFINE/D");
  AnalTree->Branch("B8_TOP_phieffFINE" &B8_TOP_phieffFINE "B8_TOP_phieffFINE/D");
  AnalTree->Branch("B8_MID_BOT_etacounterFINE" &B8_MID_BOT_etacounterFINE "B8_MID_BOT_etacounterFINE/I");
  AnalTree->Branch("B8_MID_BOT_phicounterFINE" &B8_MID_BOT_phicounterFINE "B8_MID_BOT_phicounterFINE/I");
  AnalTree->Branch("B8_TOP_etatroppilead" &B8_TOP_etatroppilead);
  AnalTree->Branch("B8_TOP_etatroppitrail" &B8_TOP_etatroppitrail);
  AnalTree->Branch("B8_TOP_phitroppilead" &B8_TOP_phitroppilead);
  AnalTree->Branch("B8_TOP_phitroppitrail" &B8_TOP_phitroppitrail);
//********************************************* Branches MID *************************************************************************
  AnalTree->Branch("B8_MID_ANDeff" &B8_MID_ANDeff "B8_MID_ANDeff/D");
  AnalTree->Branch("B8_MID_etaeff" &B8_MID_etaeff "B8_MID_etaeff/D");
  AnalTree->Branch("B8_MID_phieff" &B8_MID_phieff "B8_MID_phieff/D");
  AnalTree->Branch("B8_MID_etaeffFINE" &B8_MID_etaeffFINE "B8_MID_etaeffFINE/D");
  AnalTree->Branch("B8_MID_phieffFINE" &B8_MID_phieffFINE "B8_MID_phieffFINE/D");
  AnalTree->Branch("B8_TOP_BOT_etacounterFINE" &B8_TOP_BOT_etacounterFINE "B8_TOP_BOT_etacounterFINE/I");
  AnalTree->Branch("B8_TOP_BOT_phicounterFINE" &B8_TOP_BOT_phicounterFINE "B8_TOP_BOT_phicounterFINE/I");
  AnalTree->Branch("B8_MID_etatroppilead" &B8_MID_etatroppilead);
  AnalTree->Branch("B8_MID_etatroppitrail" &B8_MID_etatroppitrail);
  AnalTree->Branch("B8_MID_phitroppilead" &B8_MID_phitroppilead);
  AnalTree->Branch("B8_MID_phitroppitrail" &B8_MID_phitroppitrail);
//********************************************* Branches BOT *************************************************************************
  AnalTree->Branch("B8_BOT_ANDeff" &B8_BOT_ANDeff "B8_BOT_ANDeff/D");
  AnalTree->Branch("B8_BOT_etaeff" &B8_BOT_etaeff "B8_BOT_etaeff/D");
  AnalTree->Branch("B8_BOT_phieff" &B8_BOT_phieff "B8_BOT_phieff/D");
  AnalTree->Branch("B8_BOT_etaeffFINE" &B8_BOT_etaeffFINE "B8_BOT_etaeffFINE/D");
  AnalTree->Branch("B8_BOT_phieffFINE" &B8_BOT_phieffFINE "B8_BOT_phieffFINE/D");
  AnalTree->Branch("B8_TOP_MID_etacounterFINE" &B8_TOP_MID_etacounterFINE "B8_TOP_MID_etacounterFINE/I");
  AnalTree->Branch("B8_TOP_MID_phicounterFINE" &B8_TOP_MID_phicounterFINE "B8_TOP_MID_phicounterFINE/I");
  AnalTree->Branch("B8_BOT_etatroppilead" &B8_BOT_etatroppilead);
  AnalTree->Branch("B8_BOT_etatroppitrail" &B8_BOT_etatroppitrail);
  AnalTree->Branch("B8_BOT_phitroppilead" &B8_BOT_phitroppilead);
  AnalTree->Branch("B8_BOT_phitroppitrail" &B8_BOT_phitroppitrail);
  
////////////////////////////////////////////////////////////////// Maps Declarations ///////////////////////////////////////////////////
TH2D *B8_TBtrigmap = new TH2D("B8_TBtrigmap" "B8_TBtrigmap"  100 0 33 100 0 65);
TH2D *B8_MBtrigmap = new TH2D("B8_MBtrigmap" "B8_MBtrigmap"  100 0 33 100 0 65);
TH2D *B8_TMtrigmap = new TH2D("B8_TMtrigmap" "B8_TMtrigmap"  100 0 33 100 0 65);
  
  
  
  
