//********************************************* Variabili TOP *************************************************************************
std::vector<int> TOP_etafirech;
std::vector<float> TOP_etafireleading;
std::vector<int> TOP_etafiretrailch;
std::vector<float> TOP_etafiretrailing;
std::vector<float> TOP_etaWidth;
Float_t TOP_etaWidthmax;
Int_t TOP_etaWidthmaxch;
std::vector<int> TOP_phifirech;
std::vector<float> TOP_phifireleading;
std::vector<int> TOP_phifiretrailch;
std::vector<float> TOP_phifiretrailing;
std::vector<float> TOP_phiWidth;
Float_t TOP_phiWidthmax;
Int_t TOP_phiWidthmaxch;
Int_t TOP_etaevent;
Int_t TOP_etatroppilead;
Int_t TOP_etatroppitrail;
Int_t TOP_phievent;
Int_t TOP_phitroppilead;
Int_t TOP_phitroppitrail;
Int_t TOP_etanumberofclusters;
std::vector<int> TOP_etaCS;
std::vector<int> TOP_etaCSminch;
std::vector<float> TOP_etaCStime;
Int_t TOP_phinumberofclusters;
std::vector<int> TOP_phiCS;
std::vector<int> TOP_phiCSminch;
std::vector<float> TOP_phiCStime;
Double_t TOP_ANDeff;
Double_t TOP_etaeff;
Double_t TOP_phieff;
Double_t TOP_etaeffFINE;
Double_t TOP_phieffFINE;

//********************************************* Variabili MID *************************************************************************
std::vector<int> MID_etafirech;
std::vector<float> MID_etafireleading;
std::vector<int> MID_etafiretrailch;
std::vector<float> MID_etafiretrailing;
std::vector<float> MID_etaWidth;
Float_t MID_etaWidthmax;
Int_t MID_etaWidthmaxch;
std::vector<int> MID_phifirech;
std::vector<float> MID_phifireleading;
std::vector<int> MID_phifiretrailch;
std::vector<float> MID_phifiretrailing;
std::vector<float> MID_phiWidth;
Float_t MID_phiWidthmax;
Int_t MID_phiWidthmaxch;
Int_t MID_etaevent;
Int_t MID_etatroppilead;
Int_t MID_etatroppitrail;
Int_t MID_phievent;
Int_t MID_phitroppilead;
Int_t MID_phitroppitrail;
Int_t MID_etanumberofclusters;
std::vector<int> MID_etaCS;
std::vector<int> MID_etaCSminch;
std::vector<float> MID_etaCStime;
Int_t MID_phinumberofclusters;
std::vector<int> MID_phiCS;
std::vector<int> MID_phiCSminch;
std::vector<float> MID_phiCStime;
Double_t MID_ANDeff;
Double_t MID_etaeff;
Double_t MID_phieff;
Double_t MID_etaeffFINE;
Double_t MID_phieffFINE;

//********************************************* Variabili BOT *************************************************************************
std::vector<int> BOT_etafirech;
std::vector<float> BOT_etafireleading;
std::vector<int> BOT_etafiretrailch;
std::vector<float> BOT_etafiretrailing;
std::vector<float> BOT_etaWidth;
Float_t BOT_etaWidthmax;
Int_t BOT_etaWidthmaxch;
std::vector<int> BOT_phifirech;
std::vector<float> BOT_phifireleading;
std::vector<int> BOT_phifiretrailch;
std::vector<float> BOT_phifiretrailing;
std::vector<float> BOT_phiWidth;
Float_t BOT_phiWidthmax;
Int_t BOT_phiWidthmaxch;
Int_t BOT_etaevent;
Int_t BOT_etatroppilead;
Int_t BOT_etatroppitrail;
Int_t BOT_phievent;
Int_t BOT_phitroppilead;
Int_t BOT_phitroppitrail;
Int_t BOT_etanumberofclusters;
std::vector<int> BOT_etaCS;
std::vector<int> BOT_etaCSminch;
std::vector<float> BOT_etaCStime;
Int_t BOT_phinumberofclusters;
std::vector<int> BOT_phiCS;
std::vector<int> BOT_phiCSminch;
std::vector<float> BOT_phiCStime;
Double_t BOT_ANDeff;
Double_t BOT_etaeff;
Double_t BOT_phieff;
Double_t BOT_etaeffFINE;
Double_t BOT_phieffFINE;

//****************************************** VARIABILI GENERALI ***********************************
int TOP_etaeffcounter;
int TOP_etadenom;
int TOP_phieffcounter;
int TOP_phidenom;
int MID_etaeffcounter;
int MID_etadenom;
int MID_phieffcounter;
int MID_phidenom;
int BOT_etaeffcounter;
int BOT_etadenom;
int BOT_phieffcounter;
int BOT_phidenom;
////////////////////////////////////////////////////////////////// Analysis branches///////////////////////////////////////////////////
//********************************************* Branches TOP *************************************************************************
  OutTree->Branch("TOP_etafirech" &TOP_etafirech);
  OutTree->Branch("TOP_etafireleading" &TOP_etafireleading);
  OutTree->Branch("TOP_etafiretrailing" &TOP_etafiretrailing);
  OutTree->Branch("TOP_etafiretrailch" &TOP_etafiretrailch);
  OutTree->Branch("TOP_etaWidth" &TOP_etaWidth);
  OutTree->Branch("TOP_etaWidthmax" &TOP_etaWidthmax);
  OutTree->Branch("TOP_etaWidthmaxch" &TOP_etaWidthmaxch);
  OutTree->Branch("TOP_etaevent" &TOP_etaevent);
  OutTree->Branch("TOP_phifirech" &TOP_phifirech);
  OutTree->Branch("TOP_phifireleading" &TOP_phifireleading);
  OutTree->Branch("TOP_phifiretrailch" &TOP_phifiretrailch);
  OutTree->Branch("TOP_phifiretrailing" &TOP_phifiretrailing);
  OutTree->Branch("TOP_phiWidth" &TOP_phiWidth);
  OutTree->Branch("TOP_phiWidthmax" &TOP_phiWidthmax);
  OutTree->Branch("TOP_phiWidthmaxch" &TOP_phiWidthmaxch);
  OutTree->Branch("TOP_phievent" &TOP_phievent);
  OutTree->Branch("TOP_etaCS" &TOP_etaCS);
  OutTree->Branch("TOP_etanumberofclusters" &TOP_etanumberofclusters);
  OutTree->Branch("TOP_etaCStime" &TOP_etaCStime);
  OutTree->Branch("TOP_etaCSminch" &TOP_etaCSminch);
  OutTree->Branch("TOP_phiCS" &TOP_phiCS);
  OutTree->Branch("TOP_phinumberofclusters" &TOP_phinumberofclusters);
  OutTree->Branch("TOP_phiCStime" &TOP_phiCStime);
  OutTree->Branch("TOP_phiCSminch" &TOP_phiCSminch);
//********************************************* Branches MID *************************************************************************
  OutTree->Branch("MID_etafirech" &MID_etafirech);
  OutTree->Branch("MID_etafireleading" &MID_etafireleading);
  OutTree->Branch("MID_etafiretrailing" &MID_etafiretrailing);
  OutTree->Branch("MID_etafiretrailch" &MID_etafiretrailch);
  OutTree->Branch("MID_etaWidth" &MID_etaWidth);
  OutTree->Branch("MID_etaWidthmax" &MID_etaWidthmax);
  OutTree->Branch("MID_etaWidthmaxch" &MID_etaWidthmaxch);
  OutTree->Branch("MID_etaevent" &MID_etaevent);
  OutTree->Branch("MID_phifirech" &MID_phifirech);
  OutTree->Branch("MID_phifireleading" &MID_phifireleading);
  OutTree->Branch("MID_phifiretrailch" &MID_phifiretrailch);
  OutTree->Branch("MID_phifiretrailing" &MID_phifiretrailing);
  OutTree->Branch("MID_phiWidth" &MID_phiWidth);
  OutTree->Branch("MID_phiWidthmax" &MID_phiWidthmax);
  OutTree->Branch("MID_phiWidthmaxch" &MID_phiWidthmaxch);
  OutTree->Branch("MID_phievent" &MID_phievent);
  OutTree->Branch("MID_etaCS" &MID_etaCS);
  OutTree->Branch("MID_etanumberofclusters" &MID_etanumberofclusters);
  OutTree->Branch("MID_etaCStime" &MID_etaCStime);
  OutTree->Branch("MID_etaCSminch" &MID_etaCSminch);
  OutTree->Branch("MID_phiCS" &MID_phiCS);
  OutTree->Branch("MID_phinumberofclusters" &MID_phinumberofclusters);
  OutTree->Branch("MID_phiCStime" &MID_phiCStime);
  OutTree->Branch("MID_phiCSminch" &MID_phiCSminch);
//********************************************* Branches BOT *************************************************************************
  OutTree->Branch("BOT_etafirech" &BOT_etafirech);
  OutTree->Branch("BOT_etafireleading" &BOT_etafireleading);
  OutTree->Branch("BOT_etafiretrailing" &BOT_etafiretrailing);
  OutTree->Branch("BOT_etafiretrailch" &BOT_etafiretrailch);
  OutTree->Branch("BOT_etaWidth" &BOT_etaWidth);
  OutTree->Branch("BOT_etaWidthmax" &BOT_etaWidthmax);
  OutTree->Branch("BOT_etaWidthmaxch" &BOT_etaWidthmaxch);
  OutTree->Branch("BOT_etaevent" &BOT_etaevent);
  OutTree->Branch("BOT_phifirech" &BOT_phifirech);
  OutTree->Branch("BOT_phifireleading" &BOT_phifireleading);
  OutTree->Branch("BOT_phifiretrailch" &BOT_phifiretrailch);
  OutTree->Branch("BOT_phifiretrailing" &BOT_phifiretrailing);
  OutTree->Branch("BOT_phiWidth" &BOT_phiWidth);
  OutTree->Branch("BOT_phiWidthmax" &BOT_phiWidthmax);
  OutTree->Branch("BOT_phiWidthmaxch" &BOT_phiWidthmaxch);
  OutTree->Branch("BOT_phievent" &BOT_phievent);
  OutTree->Branch("BOT_etaCS" &BOT_etaCS);
  OutTree->Branch("BOT_etanumberofclusters" &BOT_etanumberofclusters);
  OutTree->Branch("BOT_etaCStime" &BOT_etaCStime);
  OutTree->Branch("BOT_etaCSminch" &BOT_etaCSminch);
  OutTree->Branch("BOT_phiCS" &BOT_phiCS);
  OutTree->Branch("BOT_phinumberofclusters" &BOT_phinumberofclusters);
  OutTree->Branch("BOT_phiCStime" &BOT_phiCStime);
  OutTree->Branch("BOT_phiCSminch" &BOT_phiCSminch);
///////////////////////////////////////////////////////////////// Ana branches///////////////////////////////////////////////////
//********************************************* Branches TOP *************************************************************************
  AnalTree->Branch("TOP_ANDeff" &TOP_ANDeff "TOP_ANDeff/D");
  AnalTree->Branch("TOP_etaeff" &TOP_etaeff "TOP_etaeff/D");
  AnalTree->Branch("TOP_phieff" &TOP_phieff "TOP_phieff/D");
  AnalTree->Branch("TOP_etaeffFINE" &TOP_etaeffFINE "TOP_etaeffFINE/D");
  AnalTree->Branch("TOP_phieffFINE" &TOP_phieffFINE "TOP_phieffFINE/D");
  AnalTree->Branch("TOP_etatroppilead" &TOP_etatroppilead);
  AnalTree->Branch("TOP_etatroppitrail" &TOP_etatroppitrail);
  AnalTree->Branch("TOP_phitroppilead" &TOP_phitroppilead);
  AnalTree->Branch("TOP_phitroppitrail" &TOP_phitroppitrail);
//********************************************* Branches MID *************************************************************************
  AnalTree->Branch("MID_ANDeff" &MID_ANDeff "MID_ANDeff/D");
  AnalTree->Branch("MID_etaeff" &MID_etaeff "MID_etaeff/D");
  AnalTree->Branch("MID_phieff" &MID_phieff "MID_phieff/D");
  AnalTree->Branch("MID_etaeffFINE" &MID_etaeffFINE "MID_etaeffFINE/D");
  AnalTree->Branch("MID_phieffFINE" &MID_phieffFINE "MID_phieffFINE/D");
  AnalTree->Branch("MID_etatroppilead" &MID_etatroppilead);
  AnalTree->Branch("MID_etatroppitrail" &MID_etatroppitrail);
  AnalTree->Branch("MID_phitroppilead" &MID_phitroppilead);
  AnalTree->Branch("MID_phitroppitrail" &MID_phitroppitrail);
//********************************************* Branches BOT *************************************************************************
  AnalTree->Branch("BOT_ANDeff" &BOT_ANDeff "BOT_ANDeff/D");
  AnalTree->Branch("BOT_etaeff" &BOT_etaeff "BOT_etaeff/D");
  AnalTree->Branch("BOT_phieff" &BOT_phieff "BOT_phieff/D");
  AnalTree->Branch("BOT_etaeffFINE" &BOT_etaeffFINE "BOT_etaeffFINE/D");
  AnalTree->Branch("BOT_phieffFINE" &BOT_phieffFINE "BOT_phieffFINE/D");
  AnalTree->Branch("BOT_etatroppilead" &BOT_etatroppilead);
  AnalTree->Branch("BOT_etatroppitrail" &BOT_etatroppitrail);
  AnalTree->Branch("BOT_phitroppilead" &BOT_phitroppilead);
  AnalTree->Branch("BOT_phitroppitrail" &BOT_phitroppitrail);
  