//********************************************* Variabili TOP *************************************************************************
std::vector<int> B7_TOP_etafirech;
std::vector<int> B7_TOP_etafirechFINE;
std::vector<float> B7_TOP_etafireleading;
std::vector<float> B7_TOP_etafireleadingFINE;
std::vector<int> B7_TOP_etafiretrailch;
std::vector<float> B7_TOP_etafiretrailing;
std::vector<float> B7_TOP_etaWidth;
std::vector<float> B7_TOP_etaWidthFINE;
Float_t B7_TOP_etaWidthmax;
Int_t B7_TOP_etaWidthmaxch;
std::vector<int> B7_TOP_phifirech;
std::vector<int> B7_TOP_phifirechFINE;
std::vector<float> B7_TOP_phifireleading;
std::vector<float> B7_TOP_phifireleadingFINE;
std::vector<int> B7_TOP_phifiretrailch;
std::vector<float> B7_TOP_phifiretrailing;
std::vector<float> B7_TOP_phiWidth;
std::vector<float> B7_TOP_phiWidthFINE;
Float_t B7_TOP_phiWidthmax;
Int_t B7_TOP_phiWidthmaxch;
Int_t B7_TOP_etaevent;
Int_t B7_TOP_etatroppilead;
Int_t B7_TOP_etatroppitrail;
Int_t B7_TOP_phievent;
Int_t B7_TOP_phitroppilead;
Int_t B7_TOP_phitroppitrail;
Int_t B7_TOP_etanumberofclusters;
std::vector<int> B7_TOP_etaCS;
std::vector<int> B7_TOP_etaCSFINE;
std::vector<int> B7_TOP_etaCSminch;
std::vector<int> B7_TOP_etaCSminchFINE;
std::vector<float> B7_TOP_etaCStime;
std::vector<float> B7_TOP_etaCStimeFINE;
Int_t B7_TOP_phinumberofclusters;
std::vector<int> B7_TOP_phiCS;
std::vector<int> B7_TOP_phiCSFINE;
std::vector<int> B7_TOP_phiCSminch;
std::vector<int> B7_TOP_phiCSminchFINE;
std::vector<float> B7_TOP_phiCStime;
std::vector<float> B7_TOP_phiCStimeFINE;
Double_t B7_TOP_ANDeff;
Double_t B7_TOP_etaeff;
Double_t B7_TOP_phieff;
Double_t B7_TOP_etaeffFINE;
Double_t B7_TOP_phieffFINE;

//********************************************* Variabili MID *************************************************************************
std::vector<int> B7_MID_etafirech;
std::vector<int> B7_MID_etafirechFINE;
std::vector<float> B7_MID_etafireleading;
std::vector<float> B7_MID_etafireleadingFINE;
std::vector<int> B7_MID_etafiretrailch;
std::vector<float> B7_MID_etafiretrailing;
std::vector<float> B7_MID_etaWidth;
std::vector<float> B7_MID_etaWidthFINE;
Float_t B7_MID_etaWidthmax;
Int_t B7_MID_etaWidthmaxch;
std::vector<int> B7_MID_phifirech;
std::vector<int> B7_MID_phifirechFINE;
std::vector<float> B7_MID_phifireleading;
std::vector<float> B7_MID_phifireleadingFINE;
std::vector<int> B7_MID_phifiretrailch;
std::vector<float> B7_MID_phifiretrailing;
std::vector<float> B7_MID_phiWidth;
std::vector<float> B7_MID_phiWidthFINE;
Float_t B7_MID_phiWidthmax;
Int_t B7_MID_phiWidthmaxch;
Int_t B7_MID_etaevent;
Int_t B7_MID_etatroppilead;
Int_t B7_MID_etatroppitrail;
Int_t B7_MID_phievent;
Int_t B7_MID_phitroppilead;
Int_t B7_MID_phitroppitrail;
Int_t B7_MID_etanumberofclusters;
std::vector<int> B7_MID_etaCS;
std::vector<int> B7_MID_etaCSFINE;
std::vector<int> B7_MID_etaCSminch;
std::vector<int> B7_MID_etaCSminchFINE;
std::vector<float> B7_MID_etaCStime;
std::vector<float> B7_MID_etaCStimeFINE;
Int_t B7_MID_phinumberofclusters;
std::vector<int> B7_MID_phiCS;
std::vector<int> B7_MID_phiCSFINE;
std::vector<int> B7_MID_phiCSminch;
std::vector<int> B7_MID_phiCSminchFINE;
std::vector<float> B7_MID_phiCStime;
std::vector<float> B7_MID_phiCStimeFINE;
Double_t B7_MID_ANDeff;
Double_t B7_MID_etaeff;
Double_t B7_MID_phieff;
Double_t B7_MID_etaeffFINE;
Double_t B7_MID_phieffFINE;

//********************************************* Variabili BOT *************************************************************************
std::vector<int> B7_BOT_etafirech;
std::vector<int> B7_BOT_etafirechFINE;
std::vector<float> B7_BOT_etafireleading;
std::vector<float> B7_BOT_etafireleadingFINE;
std::vector<int> B7_BOT_etafiretrailch;
std::vector<float> B7_BOT_etafiretrailing;
std::vector<float> B7_BOT_etaWidth;
std::vector<float> B7_BOT_etaWidthFINE;
Float_t B7_BOT_etaWidthmax;
Int_t B7_BOT_etaWidthmaxch;
std::vector<int> B7_BOT_phifirech;
std::vector<int> B7_BOT_phifirechFINE;
std::vector<float> B7_BOT_phifireleading;
std::vector<float> B7_BOT_phifireleadingFINE;
std::vector<int> B7_BOT_phifiretrailch;
std::vector<float> B7_BOT_phifiretrailing;
std::vector<float> B7_BOT_phiWidth;
std::vector<float> B7_BOT_phiWidthFINE;
Float_t B7_BOT_phiWidthmax;
Int_t B7_BOT_phiWidthmaxch;
Int_t B7_BOT_etaevent;
Int_t B7_BOT_etatroppilead;
Int_t B7_BOT_etatroppitrail;
Int_t B7_BOT_phievent;
Int_t B7_BOT_phitroppilead;
Int_t B7_BOT_phitroppitrail;
Int_t B7_BOT_etanumberofclusters;
std::vector<int> B7_BOT_etaCS;
std::vector<int> B7_BOT_etaCSFINE;
std::vector<int> B7_BOT_etaCSminch;
std::vector<int> B7_BOT_etaCSminchFINE;
std::vector<float> B7_BOT_etaCStime;
std::vector<float> B7_BOT_etaCStimeFINE;
Int_t B7_BOT_phinumberofclusters;
std::vector<int> B7_BOT_phiCS;
std::vector<int> B7_BOT_phiCSFINE;
std::vector<int> B7_BOT_phiCSminch;
std::vector<int> B7_BOT_phiCSminchFINE;
std::vector<float> B7_BOT_phiCStime;
std::vector<float> B7_BOT_phiCStimeFINE;
Double_t B7_BOT_ANDeff;
Double_t B7_BOT_etaeff;
Double_t B7_BOT_phieff;
Double_t B7_BOT_etaeffFINE;
Double_t B7_BOT_phieffFINE;

//****************************************** VARIABILI GENERALI ***********************************
int B7_Trip_etacounter;
int B7_Trip_phicounter;
int B7_TOP_BOT_etacounter;
int B7_MID_BOT_etacounter;
int B7_TOP_MID_etacounter;
int B7_TOP_BOT_phicounter;
int B7_MID_BOT_phicounter;
int B7_TOP_MID_phicounter;
int B7_TripAND_counter;
int B7_TOP_MID_ANDcounter;
int B7_TOP_BOT_ANDcounter;
int B7_MID_BOT_ANDcounter;
int B7_Trip_etacounterTOPFINE;
int B7_Trip_etacounterMIDFINE;
int B7_Trip_etacounterBOTFINE;    
int B7_TOP_BOT_etacounterFINE; 
int B7_MID_BOT_etacounterFINE; 
int B7_TOP_MID_etacounterFINE;

int B7_Trip_phicounterTOPFINE;   
int B7_Trip_phicounterMIDFINE;   
int B7_Trip_phicounterBOTFINE;    
int B7_TOP_BOT_phicounterFINE; 
int B7_MID_BOT_phicounterFINE; 
int B7_TOP_MID_phicounterFINE;

int B7_MID_BOT_etaphiflagFINE;
int B7_MID_BOT_etaphicounterFINE;
int B7_TOP_BOT_etaphiflagFINE;
int B7_TOP_BOT_etaphicounterFINE; 
int B7_TOP_MID_etaphiflagFINE;
int B7_TOP_MID_etaphicounterFINE;

////////////////////////////////////////////////////////////////// Analysis branches///////////////////////////////////////////////////
//********************************************* Branches TOP *************************************************************************
  OutTree->Branch("B7_TOP_etafirech" &B7_TOP_etafirech);
  OutTree->Branch("B7_TOP_etafirechFINE" &B7_TOP_etafirechFINE);
  OutTree->Branch("B7_TOP_etafireleading" &B7_TOP_etafireleading);
  OutTree->Branch("B7_TOP_etafireleadingFINE" &B7_TOP_etafireleadingFINE);
  OutTree->Branch("B7_TOP_etafiretrailing" &B7_TOP_etafiretrailing);
  OutTree->Branch("B7_TOP_etafiretrailch" &B7_TOP_etafiretrailch);
  OutTree->Branch("B7_TOP_etaWidth" &B7_TOP_etaWidth);
  OutTree->Branch("B7_TOP_etaWidthFINE" &B7_TOP_etaWidthFINE);
  OutTree->Branch("B7_TOP_etaWidthmax" &B7_TOP_etaWidthmax);
  OutTree->Branch("B7_TOP_etaWidthmaxch" &B7_TOP_etaWidthmaxch);
  OutTree->Branch("B7_TOP_etaevent" &B7_TOP_etaevent);
  OutTree->Branch("B7_TOP_phifirech" &B7_TOP_phifirech);
  OutTree->Branch("B7_TOP_phifirechFINE" &B7_TOP_phifirechFINE);
  OutTree->Branch("B7_TOP_phifireleading" &B7_TOP_phifireleading);
  OutTree->Branch("B7_TOP_phifireleadingFINE" &B7_TOP_phifireleadingFINE);
  OutTree->Branch("B7_TOP_phifiretrailch" &B7_TOP_phifiretrailch);
  OutTree->Branch("B7_TOP_phifiretrailing" &B7_TOP_phifiretrailing);
  OutTree->Branch("B7_TOP_phiWidth" &B7_TOP_phiWidth);
  OutTree->Branch("B7_TOP_phiWidthFINE" &B7_TOP_phiWidthFINE);
  OutTree->Branch("B7_TOP_phiWidthmax" &B7_TOP_phiWidthmax);
  OutTree->Branch("B7_TOP_phiWidthmaxch" &B7_TOP_phiWidthmaxch);
  OutTree->Branch("B7_TOP_phievent" &B7_TOP_phievent);
  OutTree->Branch("B7_TOP_etaCS" &B7_TOP_etaCS);
  OutTree->Branch("B7_TOP_etaCSFINE" &B7_TOP_etaCSFINE);
  OutTree->Branch("B7_TOP_etanumberofclusters" &B7_TOP_etanumberofclusters);
  OutTree->Branch("B7_TOP_etaCStime" &B7_TOP_etaCStime);
  OutTree->Branch("B7_TOP_etaCStimeFINE" &B7_TOP_etaCStimeFINE);
  OutTree->Branch("B7_TOP_etaCSminch" &B7_TOP_etaCSminch);
  OutTree->Branch("B7_TOP_etaCSminchFINE" &B7_TOP_etaCSminchFINE);
  OutTree->Branch("B7_TOP_phiCS" &B7_TOP_phiCS);
  OutTree->Branch("B7_TOP_phiCSFINE" &B7_TOP_phiCSFINE);
  OutTree->Branch("B7_TOP_phinumberofclusters" &B7_TOP_phinumberofclusters);
  OutTree->Branch("B7_TOP_phiCStime" &B7_TOP_phiCStime);
  OutTree->Branch("B7_TOP_phiCStimeFINE" &B7_TOP_phiCStimeFINE);
  OutTree->Branch("B7_TOP_phiCSminch" &B7_TOP_phiCSminch);
  OutTree->Branch("B7_TOP_phiCSminchFINE" &B7_TOP_phiCSminchFINE);
//********************************************* Branches MID *************************************************************************
  OutTree->Branch("B7_MID_etafirech" &B7_MID_etafirech);
  OutTree->Branch("B7_MID_etafirechFINE" &B7_MID_etafirechFINE);
  OutTree->Branch("B7_MID_etafireleading" &B7_MID_etafireleading);
  OutTree->Branch("B7_MID_etafireleadingFINE" &B7_MID_etafireleadingFINE);
  OutTree->Branch("B7_MID_etafiretrailing" &B7_MID_etafiretrailing);
  OutTree->Branch("B7_MID_etafiretrailch" &B7_MID_etafiretrailch);
  OutTree->Branch("B7_MID_etaWidth" &B7_MID_etaWidth);
  OutTree->Branch("B7_MID_etaWidthFINE" &B7_MID_etaWidthFINE);
  OutTree->Branch("B7_MID_etaWidthmax" &B7_MID_etaWidthmax);
  OutTree->Branch("B7_MID_etaWidthmaxch" &B7_MID_etaWidthmaxch);
  OutTree->Branch("B7_MID_etaevent" &B7_MID_etaevent);
  OutTree->Branch("B7_MID_phifirech" &B7_MID_phifirech);
  OutTree->Branch("B7_MID_phifirechFINE" &B7_MID_phifirechFINE);
  OutTree->Branch("B7_MID_phifireleading" &B7_MID_phifireleading);
  OutTree->Branch("B7_MID_phifireleadingFINE" &B7_MID_phifireleadingFINE);
  OutTree->Branch("B7_MID_phifiretrailch" &B7_MID_phifiretrailch);
  OutTree->Branch("B7_MID_phifiretrailing" &B7_MID_phifiretrailing);
  OutTree->Branch("B7_MID_phiWidth" &B7_MID_phiWidth);
  OutTree->Branch("B7_MID_phiWidthFINE" &B7_MID_phiWidthFINE);
  OutTree->Branch("B7_MID_phiWidthmax" &B7_MID_phiWidthmax);
  OutTree->Branch("B7_MID_phiWidthmaxch" &B7_MID_phiWidthmaxch);
  OutTree->Branch("B7_MID_phievent" &B7_MID_phievent);
  OutTree->Branch("B7_MID_etaCS" &B7_MID_etaCS);
  OutTree->Branch("B7_MID_etaCSFINE" &B7_MID_etaCSFINE);
  OutTree->Branch("B7_MID_etanumberofclusters" &B7_MID_etanumberofclusters);
  OutTree->Branch("B7_MID_etaCStime" &B7_MID_etaCStime);
  OutTree->Branch("B7_MID_etaCStimeFINE" &B7_MID_etaCStimeFINE);
  OutTree->Branch("B7_MID_etaCSminch" &B7_MID_etaCSminch);
  OutTree->Branch("B7_MID_etaCSminchFINE" &B7_MID_etaCSminchFINE);
  OutTree->Branch("B7_MID_phiCS" &B7_MID_phiCS);
  OutTree->Branch("B7_MID_phiCSFINE" &B7_MID_phiCSFINE);
  OutTree->Branch("B7_MID_phinumberofclusters" &B7_MID_phinumberofclusters);
  OutTree->Branch("B7_MID_phiCStime" &B7_MID_phiCStime);
  OutTree->Branch("B7_MID_phiCStimeFINE" &B7_MID_phiCStimeFINE);
  OutTree->Branch("B7_MID_phiCSminch" &B7_MID_phiCSminch);
  OutTree->Branch("B7_MID_phiCSminchFINE" &B7_MID_phiCSminchFINE);
//********************************************* Branches BOT *************************************************************************
  OutTree->Branch("B7_BOT_etafirech" &B7_BOT_etafirech);
  OutTree->Branch("B7_BOT_etafirechFINE" &B7_BOT_etafirechFINE);
  OutTree->Branch("B7_BOT_etafireleading" &B7_BOT_etafireleading);
  OutTree->Branch("B7_BOT_etafireleadingFINE" &B7_BOT_etafireleadingFINE);
  OutTree->Branch("B7_BOT_etafiretrailing" &B7_BOT_etafiretrailing);
  OutTree->Branch("B7_BOT_etafiretrailch" &B7_BOT_etafiretrailch);
  OutTree->Branch("B7_BOT_etaWidth" &B7_BOT_etaWidth);
  OutTree->Branch("B7_BOT_etaWidthFINE" &B7_BOT_etaWidthFINE);
  OutTree->Branch("B7_BOT_etaWidthmax" &B7_BOT_etaWidthmax);
  OutTree->Branch("B7_BOT_etaWidthmaxch" &B7_BOT_etaWidthmaxch);
  OutTree->Branch("B7_BOT_etaevent" &B7_BOT_etaevent);
  OutTree->Branch("B7_BOT_phifirech" &B7_BOT_phifirech);
  OutTree->Branch("B7_BOT_phifirechFINE" &B7_BOT_phifirechFINE);
  OutTree->Branch("B7_BOT_phifireleading" &B7_BOT_phifireleading);
  OutTree->Branch("B7_BOT_phifireleadingFINE" &B7_BOT_phifireleadingFINE);
  OutTree->Branch("B7_BOT_phifiretrailch" &B7_BOT_phifiretrailch);
  OutTree->Branch("B7_BOT_phifiretrailing" &B7_BOT_phifiretrailing);
  OutTree->Branch("B7_BOT_phiWidth" &B7_BOT_phiWidth);
  OutTree->Branch("B7_BOT_phiWidthFINE" &B7_BOT_phiWidthFINE);
  OutTree->Branch("B7_BOT_phiWidthmax" &B7_BOT_phiWidthmax);
  OutTree->Branch("B7_BOT_phiWidthmaxch" &B7_BOT_phiWidthmaxch);
  OutTree->Branch("B7_BOT_phievent" &B7_BOT_phievent);
  OutTree->Branch("B7_BOT_etaCS" &B7_BOT_etaCS);
  OutTree->Branch("B7_BOT_etaCSFINE" &B7_BOT_etaCSFINE);
  OutTree->Branch("B7_BOT_etanumberofclusters" &B7_BOT_etanumberofclusters);
  OutTree->Branch("B7_BOT_etaCStime" &B7_BOT_etaCStime);
  OutTree->Branch("B7_BOT_etaCStimeFINE" &B7_BOT_etaCStimeFINE);
  OutTree->Branch("B7_BOT_etaCSminch" &B7_BOT_etaCSminch);
  OutTree->Branch("B7_BOT_etaCSminchFINE" &B7_BOT_etaCSminchFINE);
  OutTree->Branch("B7_BOT_phiCS" &B7_BOT_phiCS);
  OutTree->Branch("B7_BOT_phiCSFINE" &B7_BOT_phiCSFINE);
  OutTree->Branch("B7_BOT_phinumberofclusters" &B7_BOT_phinumberofclusters);
  OutTree->Branch("B7_BOT_phiCStime" &B7_BOT_phiCStime);
  OutTree->Branch("B7_BOT_phiCStimeFINE" &B7_BOT_phiCStimeFINE);
  OutTree->Branch("B7_BOT_phiCSminch" &B7_BOT_phiCSminch);
  OutTree->Branch("B7_BOT_phiCSminchFINE" &B7_BOT_phiCSminchFINE);
///////////////////////////////////////////////////////////////// Ana branches///////////////////////////////////////////////////
//********************************************* Branches TOP *************************************************************************
  AnalTree->Branch("B7_TOP_ANDeff" &B7_TOP_ANDeff "B7_TOP_ANDeff/D");
  AnalTree->Branch("B7_TOP_etaeff" &B7_TOP_etaeff "B7_TOP_etaeff/D");
  AnalTree->Branch("B7_TOP_phieff" &B7_TOP_phieff "B7_TOP_phieff/D");
  AnalTree->Branch("B7_TOP_etaeffFINE" &B7_TOP_etaeffFINE "B7_TOP_etaeffFINE/D");
  AnalTree->Branch("B7_TOP_phieffFINE" &B7_TOP_phieffFINE "B7_TOP_phieffFINE/D");
  AnalTree->Branch("B7_MID_BOT_etacounterFINE" &B7_MID_BOT_etacounterFINE "B7_MID_BOT_etacounterFINE/I");
  AnalTree->Branch("B7_MID_BOT_phicounterFINE" &B7_MID_BOT_phicounterFINE "B7_MID_BOT_phicounterFINE/I");
  AnalTree->Branch("B7_TOP_etatroppilead" &B7_TOP_etatroppilead);
  AnalTree->Branch("B7_TOP_etatroppitrail" &B7_TOP_etatroppitrail);
  AnalTree->Branch("B7_TOP_phitroppilead" &B7_TOP_phitroppilead);
  AnalTree->Branch("B7_TOP_phitroppitrail" &B7_TOP_phitroppitrail);
//********************************************* Branches MID *************************************************************************
  AnalTree->Branch("B7_MID_ANDeff" &B7_MID_ANDeff "B7_MID_ANDeff/D");
  AnalTree->Branch("B7_MID_etaeff" &B7_MID_etaeff "B7_MID_etaeff/D");
  AnalTree->Branch("B7_MID_phieff" &B7_MID_phieff "B7_MID_phieff/D");
  AnalTree->Branch("B7_MID_etaeffFINE" &B7_MID_etaeffFINE "B7_MID_etaeffFINE/D");
  AnalTree->Branch("B7_MID_phieffFINE" &B7_MID_phieffFINE "B7_MID_phieffFINE/D");
  AnalTree->Branch("B7_TOP_BOT_etacounterFINE" &B7_TOP_BOT_etacounterFINE "B7_TOP_BOT_etacounterFINE/I");
  AnalTree->Branch("B7_TOP_BOT_phicounterFINE" &B7_TOP_BOT_phicounterFINE "B7_TOP_BOT_phicounterFINE/I");
  AnalTree->Branch("B7_MID_etatroppilead" &B7_MID_etatroppilead);
  AnalTree->Branch("B7_MID_etatroppitrail" &B7_MID_etatroppitrail);
  AnalTree->Branch("B7_MID_phitroppilead" &B7_MID_phitroppilead);
  AnalTree->Branch("B7_MID_phitroppitrail" &B7_MID_phitroppitrail);
//********************************************* Branches BOT *************************************************************************
  AnalTree->Branch("B7_BOT_ANDeff" &B7_BOT_ANDeff "B7_BOT_ANDeff/D");
  AnalTree->Branch("B7_BOT_etaeff" &B7_BOT_etaeff "B7_BOT_etaeff/D");
  AnalTree->Branch("B7_BOT_phieff" &B7_BOT_phieff "B7_BOT_phieff/D");
  AnalTree->Branch("B7_BOT_etaeffFINE" &B7_BOT_etaeffFINE "B7_BOT_etaeffFINE/D");
  AnalTree->Branch("B7_BOT_phieffFINE" &B7_BOT_phieffFINE "B7_BOT_phieffFINE/D");
  AnalTree->Branch("B7_TOP_MID_etacounterFINE" &B7_TOP_MID_etacounterFINE "B7_TOP_MID_etacounterFINE/I");
  AnalTree->Branch("B7_TOP_MID_phicounterFINE" &B7_TOP_MID_phicounterFINE "B7_TOP_MID_phicounterFINE/I");
  AnalTree->Branch("B7_BOT_etatroppilead" &B7_BOT_etatroppilead);
  AnalTree->Branch("B7_BOT_etatroppitrail" &B7_BOT_etatroppitrail);
  AnalTree->Branch("B7_BOT_phitroppilead" &B7_BOT_phitroppilead);
  AnalTree->Branch("B7_BOT_phitroppitrail" &B7_BOT_phitroppitrail);

////////////////////////////////////////////////////////////////// Maps Declarations ///////////////////////////////////////////////////
TH2D *B7_TBtrigmap = new TH2D("B7_TBtrigmap" "B7_TBtrigmap"  100 0 33 100 0 65);
TH2D *B7_MBtrigmap = new TH2D("B7_MBtrigmap" "B7_MBtrigmap"  100 0 33 100 0 65);
TH2D *B7_TMtrigmap = new TH2D("B7_TMtrigmap" "B7_TMtrigmap"  100 0 33 100 0 65);

  
